# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accelerationsense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='accelerationsense.proto',
  package='AccelerationSense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x61\x63\x63\x65lerationsense.proto\x12\x11\x41\x63\x63\x65lerationSense\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n\x12\x41\x63\x63\x65lerationQuanta\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12J\n\x07profile\x18\x02 \x01(\x0b\x32\x39.AccelerationSense.AccelerationQuanta.AccelerationProfile\x1a\x39\n\x13\x41\x63\x63\x65lerationProfile\x12\n\n\x02\x61x\x18\x01 \x01(\x02\x12\n\n\x02\x61y\x18\x02 \x01(\x02\x12\n\n\x02\x61z\x18\x03 \x01(\x02\"I\n\x0f\x41\x63\x63\x65lerationLog\x12\x36\n\x07quantas\x18\x01 \x03(\x0b\x32%.AccelerationSense.AccelerationQuantab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ACCELERATIONQUANTA_ACCELERATIONPROFILE = _descriptor.Descriptor(
  name='AccelerationProfile',
  full_name='AccelerationSense.AccelerationQuanta.AccelerationProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ax', full_name='AccelerationSense.AccelerationQuanta.AccelerationProfile.ax', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ay', full_name='AccelerationSense.AccelerationQuanta.AccelerationProfile.ay', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='az', full_name='AccelerationSense.AccelerationQuanta.AccelerationProfile.az', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=277,
)

_ACCELERATIONQUANTA = _descriptor.Descriptor(
  name='AccelerationQuanta',
  full_name='AccelerationSense.AccelerationQuanta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='AccelerationSense.AccelerationQuanta.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='AccelerationSense.AccelerationQuanta.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ACCELERATIONQUANTA_ACCELERATIONPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=277,
)


_ACCELERATIONLOG = _descriptor.Descriptor(
  name='AccelerationLog',
  full_name='AccelerationSense.AccelerationLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantas', full_name='AccelerationSense.AccelerationLog.quantas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=352,
)

_ACCELERATIONQUANTA_ACCELERATIONPROFILE.containing_type = _ACCELERATIONQUANTA
_ACCELERATIONQUANTA.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ACCELERATIONQUANTA.fields_by_name['profile'].message_type = _ACCELERATIONQUANTA_ACCELERATIONPROFILE
_ACCELERATIONLOG.fields_by_name['quantas'].message_type = _ACCELERATIONQUANTA
DESCRIPTOR.message_types_by_name['AccelerationQuanta'] = _ACCELERATIONQUANTA
DESCRIPTOR.message_types_by_name['AccelerationLog'] = _ACCELERATIONLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccelerationQuanta = _reflection.GeneratedProtocolMessageType('AccelerationQuanta', (_message.Message,), dict(

  AccelerationProfile = _reflection.GeneratedProtocolMessageType('AccelerationProfile', (_message.Message,), dict(
    DESCRIPTOR = _ACCELERATIONQUANTA_ACCELERATIONPROFILE,
    __module__ = 'accelerationsense_pb2'
    # @@protoc_insertion_point(class_scope:AccelerationSense.AccelerationQuanta.AccelerationProfile)
    ))
  ,
  DESCRIPTOR = _ACCELERATIONQUANTA,
  __module__ = 'accelerationsense_pb2'
  # @@protoc_insertion_point(class_scope:AccelerationSense.AccelerationQuanta)
  ))
_sym_db.RegisterMessage(AccelerationQuanta)
_sym_db.RegisterMessage(AccelerationQuanta.AccelerationProfile)

AccelerationLog = _reflection.GeneratedProtocolMessageType('AccelerationLog', (_message.Message,), dict(
  DESCRIPTOR = _ACCELERATIONLOG,
  __module__ = 'accelerationsense_pb2'
  # @@protoc_insertion_point(class_scope:AccelerationSense.AccelerationLog)
  ))
_sym_db.RegisterMessage(AccelerationLog)


# @@protoc_insertion_point(module_scope)
