# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microphonesense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='microphonesense.proto',
  package='MicrophoneSense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15microphonesense.proto\x12\x0fMicrophoneSense\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n\x10MicrophoneQuanta\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12J\n\x07profile\x18\x02 \x01(\x0b\x32\x39.MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile\x1aj\n\x17MicrophoneSampleProfile\x12\x12\n\ntotal_time\x18\x01 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\x12\x11\n\tbit_depth\x18\x03 \x01(\x05\x12\x13\n\x0bmic_samples\x18\x04 \x01(\x0c\"C\n\rMicrophoneLog\x12\x32\n\x07quantas\x18\x01 \x03(\x0b\x32!.MicrophoneSense.MicrophoneQuantab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MICROPHONEQUANTA_MICROPHONESAMPLEPROFILE = _descriptor.Descriptor(
  name='MicrophoneSampleProfile',
  full_name='MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_time', full_name='MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile.total_time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile.num_samples', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bit_depth', full_name='MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile.bit_depth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mic_samples', full_name='MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile.mic_samples', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=320,
)

_MICROPHONEQUANTA = _descriptor.Descriptor(
  name='MicrophoneQuanta',
  full_name='MicrophoneSense.MicrophoneQuanta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MicrophoneSense.MicrophoneQuanta.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='MicrophoneSense.MicrophoneQuanta.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MICROPHONEQUANTA_MICROPHONESAMPLEPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=320,
)


_MICROPHONELOG = _descriptor.Descriptor(
  name='MicrophoneLog',
  full_name='MicrophoneSense.MicrophoneLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantas', full_name='MicrophoneSense.MicrophoneLog.quantas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=389,
)

_MICROPHONEQUANTA_MICROPHONESAMPLEPROFILE.containing_type = _MICROPHONEQUANTA
_MICROPHONEQUANTA.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MICROPHONEQUANTA.fields_by_name['profile'].message_type = _MICROPHONEQUANTA_MICROPHONESAMPLEPROFILE
_MICROPHONELOG.fields_by_name['quantas'].message_type = _MICROPHONEQUANTA
DESCRIPTOR.message_types_by_name['MicrophoneQuanta'] = _MICROPHONEQUANTA
DESCRIPTOR.message_types_by_name['MicrophoneLog'] = _MICROPHONELOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MicrophoneQuanta = _reflection.GeneratedProtocolMessageType('MicrophoneQuanta', (_message.Message,), dict(

  MicrophoneSampleProfile = _reflection.GeneratedProtocolMessageType('MicrophoneSampleProfile', (_message.Message,), dict(
    DESCRIPTOR = _MICROPHONEQUANTA_MICROPHONESAMPLEPROFILE,
    __module__ = 'microphonesense_pb2'
    # @@protoc_insertion_point(class_scope:MicrophoneSense.MicrophoneQuanta.MicrophoneSampleProfile)
    ))
  ,
  DESCRIPTOR = _MICROPHONEQUANTA,
  __module__ = 'microphonesense_pb2'
  # @@protoc_insertion_point(class_scope:MicrophoneSense.MicrophoneQuanta)
  ))
_sym_db.RegisterMessage(MicrophoneQuanta)
_sym_db.RegisterMessage(MicrophoneQuanta.MicrophoneSampleProfile)

MicrophoneLog = _reflection.GeneratedProtocolMessageType('MicrophoneLog', (_message.Message,), dict(
  DESCRIPTOR = _MICROPHONELOG,
  __module__ = 'microphonesense_pb2'
  # @@protoc_insertion_point(class_scope:MicrophoneSense.MicrophoneLog)
  ))
_sym_db.RegisterMessage(MicrophoneLog)


# @@protoc_insertion_point(module_scope)
