# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: positionsense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='positionsense.proto',
  package='PositiionSense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13positionsense.proto\x12\x0ePositiionSense\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n\x0fPositiionQuanta\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x41\n\x07profile\x18\x02 \x01(\x0b\x32\x30.PositiionSense.PositiionQuanta.PositiionProfile\x1a\x33\n\x10PositiionProfile\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"@\n\x0cPositiionLog\x12\x30\n\x07quantas\x18\x01 \x03(\x0b\x32\x1f.PositiionSense.PositiionQuantab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_POSITIIONQUANTA_POSITIIONPROFILE = _descriptor.Descriptor(
  name='PositiionProfile',
  full_name='PositiionSense.PositiionQuanta.PositiionProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PositiionSense.PositiionQuanta.PositiionProfile.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PositiionSense.PositiionQuanta.PositiionProfile.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PositiionSense.PositiionQuanta.PositiionProfile.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=252,
)

_POSITIIONQUANTA = _descriptor.Descriptor(
  name='PositiionQuanta',
  full_name='PositiionSense.PositiionQuanta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='PositiionSense.PositiionQuanta.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='PositiionSense.PositiionQuanta.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSITIIONQUANTA_POSITIIONPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=252,
)


_POSITIIONLOG = _descriptor.Descriptor(
  name='PositiionLog',
  full_name='PositiionSense.PositiionLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantas', full_name='PositiionSense.PositiionLog.quantas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=318,
)

_POSITIIONQUANTA_POSITIIONPROFILE.containing_type = _POSITIIONQUANTA
_POSITIIONQUANTA.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_POSITIIONQUANTA.fields_by_name['profile'].message_type = _POSITIIONQUANTA_POSITIIONPROFILE
_POSITIIONLOG.fields_by_name['quantas'].message_type = _POSITIIONQUANTA
DESCRIPTOR.message_types_by_name['PositiionQuanta'] = _POSITIIONQUANTA
DESCRIPTOR.message_types_by_name['PositiionLog'] = _POSITIIONLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PositiionQuanta = _reflection.GeneratedProtocolMessageType('PositiionQuanta', (_message.Message,), dict(

  PositiionProfile = _reflection.GeneratedProtocolMessageType('PositiionProfile', (_message.Message,), dict(
    DESCRIPTOR = _POSITIIONQUANTA_POSITIIONPROFILE,
    __module__ = 'positionsense_pb2'
    # @@protoc_insertion_point(class_scope:PositiionSense.PositiionQuanta.PositiionProfile)
    ))
  ,
  DESCRIPTOR = _POSITIIONQUANTA,
  __module__ = 'positionsense_pb2'
  # @@protoc_insertion_point(class_scope:PositiionSense.PositiionQuanta)
  ))
_sym_db.RegisterMessage(PositiionQuanta)
_sym_db.RegisterMessage(PositiionQuanta.PositiionProfile)

PositiionLog = _reflection.GeneratedProtocolMessageType('PositiionLog', (_message.Message,), dict(
  DESCRIPTOR = _POSITIIONLOG,
  __module__ = 'positionsense_pb2'
  # @@protoc_insertion_point(class_scope:PositiionSense.PositiionLog)
  ))
_sym_db.RegisterMessage(PositiionLog)


# @@protoc_insertion_point(module_scope)
