# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rotationsense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rotationsense.proto',
  package='RotationSense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13rotationsense.proto\x12\rRotationSense\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n\x0eRotationQuanta\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12>\n\x07profile\x18\x02 \x01(\x0b\x32-.RotationSense.RotationQuanta.RotationProfile\x1a\x35\n\x0fRotationProfile\x12\n\n\x02rx\x18\x01 \x01(\x02\x12\n\n\x02ry\x18\x02 \x01(\x02\x12\n\n\x02rz\x18\x03 \x01(\x02\"=\n\x0bRotationLog\x12.\n\x07quantas\x18\x01 \x03(\x0b\x32\x1d.RotationSense.RotationQuantab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ROTATIONQUANTA_ROTATIONPROFILE = _descriptor.Descriptor(
  name='RotationProfile',
  full_name='RotationSense.RotationQuanta.RotationProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rx', full_name='RotationSense.RotationQuanta.RotationProfile.rx', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ry', full_name='RotationSense.RotationQuanta.RotationProfile.ry', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rz', full_name='RotationSense.RotationQuanta.RotationProfile.rz', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=249,
)

_ROTATIONQUANTA = _descriptor.Descriptor(
  name='RotationQuanta',
  full_name='RotationSense.RotationQuanta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='RotationSense.RotationQuanta.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='RotationSense.RotationQuanta.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROTATIONQUANTA_ROTATIONPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=249,
)


_ROTATIONLOG = _descriptor.Descriptor(
  name='RotationLog',
  full_name='RotationSense.RotationLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantas', full_name='RotationSense.RotationLog.quantas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=312,
)

_ROTATIONQUANTA_ROTATIONPROFILE.containing_type = _ROTATIONQUANTA
_ROTATIONQUANTA.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ROTATIONQUANTA.fields_by_name['profile'].message_type = _ROTATIONQUANTA_ROTATIONPROFILE
_ROTATIONLOG.fields_by_name['quantas'].message_type = _ROTATIONQUANTA
DESCRIPTOR.message_types_by_name['RotationQuanta'] = _ROTATIONQUANTA
DESCRIPTOR.message_types_by_name['RotationLog'] = _ROTATIONLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RotationQuanta = _reflection.GeneratedProtocolMessageType('RotationQuanta', (_message.Message,), dict(

  RotationProfile = _reflection.GeneratedProtocolMessageType('RotationProfile', (_message.Message,), dict(
    DESCRIPTOR = _ROTATIONQUANTA_ROTATIONPROFILE,
    __module__ = 'rotationsense_pb2'
    # @@protoc_insertion_point(class_scope:RotationSense.RotationQuanta.RotationProfile)
    ))
  ,
  DESCRIPTOR = _ROTATIONQUANTA,
  __module__ = 'rotationsense_pb2'
  # @@protoc_insertion_point(class_scope:RotationSense.RotationQuanta)
  ))
_sym_db.RegisterMessage(RotationQuanta)
_sym_db.RegisterMessage(RotationQuanta.RotationProfile)

RotationLog = _reflection.GeneratedProtocolMessageType('RotationLog', (_message.Message,), dict(
  DESCRIPTOR = _ROTATIONLOG,
  __module__ = 'rotationsense_pb2'
  # @@protoc_insertion_point(class_scope:RotationSense.RotationLog)
  ))
_sym_db.RegisterMessage(RotationLog)


# @@protoc_insertion_point(module_scope)
