# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifisense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wifisense.proto',
  package='WifiSense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fwifisense.proto\x12\tWifiSense\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n\nWifiQuanta\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x08profiles\x18\x02 \x03(\x0b\x32!.WifiSense.WifiQuanta.WifiProfile\x1a*\n\x0bWifiProfile\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\r\n\x05\x62ssid\x18\x02 \x01(\t\"1\n\x07WifiLog\x12&\n\x07quantas\x18\x01 \x03(\x0b\x32\x15.WifiSense.WifiQuantab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WIFIQUANTA_WIFIPROFILE = _descriptor.Descriptor(
  name='WifiProfile',
  full_name='WifiSense.WifiQuanta.WifiProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='WifiSense.WifiQuanta.WifiProfile.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bssid', full_name='WifiSense.WifiQuanta.WifiProfile.bssid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=215,
)

_WIFIQUANTA = _descriptor.Descriptor(
  name='WifiQuanta',
  full_name='WifiSense.WifiQuanta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='WifiSense.WifiQuanta.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profiles', full_name='WifiSense.WifiQuanta.profiles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WIFIQUANTA_WIFIPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=215,
)


_WIFILOG = _descriptor.Descriptor(
  name='WifiLog',
  full_name='WifiSense.WifiLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantas', full_name='WifiSense.WifiLog.quantas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=266,
)

_WIFIQUANTA_WIFIPROFILE.containing_type = _WIFIQUANTA
_WIFIQUANTA.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WIFIQUANTA.fields_by_name['profiles'].message_type = _WIFIQUANTA_WIFIPROFILE
_WIFILOG.fields_by_name['quantas'].message_type = _WIFIQUANTA
DESCRIPTOR.message_types_by_name['WifiQuanta'] = _WIFIQUANTA
DESCRIPTOR.message_types_by_name['WifiLog'] = _WIFILOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WifiQuanta = _reflection.GeneratedProtocolMessageType('WifiQuanta', (_message.Message,), dict(

  WifiProfile = _reflection.GeneratedProtocolMessageType('WifiProfile', (_message.Message,), dict(
    DESCRIPTOR = _WIFIQUANTA_WIFIPROFILE,
    __module__ = 'wifisense_pb2'
    # @@protoc_insertion_point(class_scope:WifiSense.WifiQuanta.WifiProfile)
    ))
  ,
  DESCRIPTOR = _WIFIQUANTA,
  __module__ = 'wifisense_pb2'
  # @@protoc_insertion_point(class_scope:WifiSense.WifiQuanta)
  ))
_sym_db.RegisterMessage(WifiQuanta)
_sym_db.RegisterMessage(WifiQuanta.WifiProfile)

WifiLog = _reflection.GeneratedProtocolMessageType('WifiLog', (_message.Message,), dict(
  DESCRIPTOR = _WIFILOG,
  __module__ = 'wifisense_pb2'
  # @@protoc_insertion_point(class_scope:WifiSense.WifiLog)
  ))
_sym_db.RegisterMessage(WifiLog)


# @@protoc_insertion_point(module_scope)
